name: students_attendance_app_mlkit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  intl: ^0.20.2
  lottie: ^3.3.1
  google_mlkit_face_detection: ^0.12.0
  dotted_border: ^2.1.0
  geolocator: ^13.0.2
  cloud_firestore: ^5.6.2
  geocoding: ^3.0.0
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/raw/
